### PR TITLE
React Assignment Completed

### PR DESCRIPTION
**Pull request by kedarshenoy**
React  Assignment  along  with backend

### CODE REVIEW

**Comment by Saurabh7379** [comment]
Bro, you have written great code. In React you could have used functional components instead of class components because it makes code more modular and its more in use. Never commit node_modules folder you can add the folder removal in .gitignore file and it will not commit that folder because that folder is very heavy and can be generated just by running npm install command on the machine where we want to run the code.

**Comment by kedarshenoy** [comment]
I wanted to express my sincere gratitude for taking the time to review it.
I must admit that at the time of submitting the PR, I was still in the learning phase with React, and I inadvertently used an older version. Additionally, I wasn't aware of the best practices, such as avoiding the inclusion of node_modules in the GitHub repository, and I was unfamiliar with the concept of functional components.

Your constructive feedback has been precious Once again, thank you for your feedback

**Comment by kedarshenoy** [comment]
> Bro, you have written great code. In React you could have used functional components instead of class components because it makes code more modular and its more in use. Never commit node_modules folder you can add the folder removal in .gitignore file and it will not commit that folder because that folder is very heavy and can be generated just by running npm install command on the machine where we want to run the code.

**Comment by kedarshenoy** [comment]
I wanted to express my sincere gratitude for taking the time to review it.
I must admit that at the time of submitting the PR, I was still in the learning phase with React, and I inadvertently used an older version. Additionally, I wasn't aware of the best practices, such as avoiding the inclusion of node_modules in the GitHub repository, and I was unfamiliar with the concept of functional components.

Your constructive feedback has been precious Once again, thank you for your feedback

**Pull request closed without merging**
